package com.roman.taskoop.entity;

public enum TypeOfAppliances {
    WASHING_MACHINE, TUMBLE_DRYER, IRON, FRIDGE, FREEZER, WINE_COOLER, DISHWASHER, HOB, OVEN, COOKER, MICROVAWE, TV,
    AUDIO_SYSTEM, GAME_CONSOLE, STEAM_CLEANER, VACUUM_CLEANER, KETTLE, TOASTER, BLANDER, MIXER, MULTI_COOKER,
    COFFEE_MACHINE, HAIR_DRYER, TRIMMER, RAZOR, HAIR_CLIPPER;
}
